### ISSUE TITLE
zabbix template might be outdated 

### ISSUE THREAD

**Issue by joergmschulz** [tiredofit/docker-postgres#5]
After adding 

`shared_preload_libraries = 'pg_stat_statements'`
to the postgresql.conf, 
and after 
CREATE EXTENSION pg_stat_statements;
I can find the view pg_stat_statements, but it doesn't have the column total_time (see https://www.postgresql.org/docs/13//pgstatstatements.html ).

Thus
`select round((sum(total_time) / sum(calls))::numeric,2) from pg_stat_statements;
`
from the monitoring script fails.

Similar for `function pg_current_xlog_location() does not exist`

((( sorry for posting so many issues )))

**Comment by tiredofit** [comment]
No problem about too many issues, this is great motivation to start getting my stuff back in order to the public. I actually dont have a good template right now so will have to sit down and write one and revamp how things work ... If you find a good one I am more than happy to swap it out!

I'm just actually glad that you are getting some good mileage on some of my mostly undocumented images!

**Comment by tiredofit** [comment]
`15-3.0.0` is a total rewrite and now includes support for the Zabbix Agent 2 :)

**Comment by joergmschulz** [comment]
let's give that a try ....
